// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUKEcr4mNoR9YZe5Q6qWBeKCKxkCrmxmQ',
    appId: '1:616483723793:web:7316bcb2d6e7fdbeac2fb0',
    messagingSenderId: '616483723793',
    projectId: 'roadapp-7f30d',
    authDomain: 'roadapp-7f30d.firebaseapp.com',
    storageBucket: 'roadapp-7f30d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7pYMvl2b7sHaONwYl1x26jGWVzxxd1J0',
    appId: '1:616483723793:android:7560703cbe10ba2cac2fb0',
    messagingSenderId: '616483723793',
    projectId: 'roadapp-7f30d',
    storageBucket: 'roadapp-7f30d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDUbKs2UGCrAMyhGps_5E-4onB5-w04Gk',
    appId: '1:616483723793:ios:61d2c8f4fdbfaa14ac2fb0',
    messagingSenderId: '616483723793',
    projectId: 'roadapp-7f30d',
    storageBucket: 'roadapp-7f30d.firebasestorage.app',
    iosBundleId: 'com.example.taraApp',
  );
}
